# Generated by Django 5.2.6 on 2025-09-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vat", models.DecimalField(decimal_places=2, max_digits=2)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("available", models.BooleanField(default=True)),
            ],
        ),
    ]
